### ISSUE TITLE
"TRPCError: Could not validate access token." error on Node 19

### ISSUE THREAD

**Issue by JLarky** [fogbender/b2b-saaskit#106]
```
TRPCError: Could not validate access token.
    at eval (/.../b2b-saaskit/src/lib/trpc/trpc.ts:91:11)
    at async callRecursive (file:///.../b2b-saaskit/node_modules/@trpc/server/dist/index.mjs:452:32)
    at async callRecursive (file:///.../b2b-saaskit/node_modules/@trpc/server/dist/index.mjs:452:32)
    at async resolve (file:///.../b2b-saaskit/node_modules/@trpc/server/dist/index.mjs:482:24) {
  code: 'UNAUTHORIZED',
  [cause]: UnauthorizedException [Error]: jwt malformed
      at verifyToken (/.../b2b-saaskit/node_modules/@propelauth/node/dist/index.js:23063:19)
      at /.../b2b-saaskit/node_modules/@propelauth/node/dist/index.js:23039:16
      at Generator.next (<anonymous>)
      at fulfilled (/.../b2b-saaskit/node_modules/@propelauth/node/dist/index.js:37:58) {
    status: 401
  }
}
```

it looks like `set-cookie` header doesn't work in Node 19, but it was working in 18 and was fixed in 20 

https://github.com/nodejs/node/issues/47755

We are calling `ctx.resHeaders.append('set-cookie', ...)` twice and only one of them would be applied in Node 19.

It looks like that in 19:

![IMAGE 2023-06-26 17:26:37](https://github.com/fogbender/b2b-saaskit/assets/7026/5b84e167-5705-4dbb-a52d-523be63115f6)

And it looks like this in 18 or 20 (you see two cookies set):

![IMAGE 2023-06-26 17:26:54](https://github.com/fogbender/b2b-saaskit/assets/7026/eec769ad-dc33-4c90-abbc-98ef73a7348d)

**Comment by JLarky** [comment]
Closing, because it's an issue with Node
